In [1]:
import numpy as np


In [2]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.shape

(10,)

In [4]:
x.ndim

1

In [5]:
x_new=x.reshape(10,1)
x_new

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
x_new.shape

(10, 1)

In [8]:
x_new.ndim

2

In [9]:
x_new=x.reshape(-1,1)
x_new

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
x_new.shape

(10, 1)

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x_new=x.reshape(1,10)
x_new

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
x_new=x.reshape(1,-1)
x_new

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])