# Nominal variable - Without any particular impiled order like say color of eyes
- Black, Blue, Green Brown. There is no ranking or ordering to colors
person's gender marital status, hometown, or the types of movies...

**Ordinal Categorical** - It occurs with a natural ordering.
like size(small,medium,large), exam grades, movies ratings...

**Discrete data** represents items that can be counted;

**Continuos data** has infinite no of possible values

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame([['green','L',10.30,'class1'],['red','M',12.30,'class2'],
                  ['blue','XL',18.30,'class3']])

df.columns= ['Color','Size','Price','Target']
df

Color Size  Price  Target
0  green    L   10.3  class1
1    red    M   12.3  class2
2   blue   XL   18.3  class3

XL>L>M then make sense (ordinal data)

green>red>blue...no comparision possible i.e does not make any sense

(nominal data)

In [4]:
size_mapping = {'M':1,'L':2,'XL':3} #label encoding using map method

In [5]:
df['Size']= df['Size'].map(size_mapping)

In [6]:
df #categorical data is convertd into nominal data

Color  Size  Price  Target
0  green     2   10.3  class1
1    red     1   12.3  class2
2   blue     3   18.3  class3

In [7]:
df[df.columns[:-1]]

Color  Size  Price
0  green     2   10.3
1    red     1   12.3
2   blue     3   18.3

In [8]:
#create dummy variables
df2 = pd.get_dummies(df[df.columns[:-1]],dtype=int)

In [9]:
df2

Size  Price  Color_blue  Color_green  Color_red
0     2   10.3           0            1          0
1     1   12.3           0            0          1
2     3   18.3           1            0          0

#also called one hot encoding, it apply only input data or featues.

In [14]:
# Label encoding apply on target data or output data & 
# target always 1 dimensional,
# only 1 value.
df2['target']=df.Target.map({'class1':0,'class2':1,'class3':2})


In [15]:
df2

Size  Price  Color_blue  Color_green  Color_red  target
0     2   10.3           0            1          0       0
1     1   12.3           0            0          1       1
2     3   18.3           1            0          0       2

# Label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
labels=['setosa','versicolor','virginica']


In [3]:
labels

['setosa', 'versicolor', 'virginica']

In [4]:
encoder = LabelEncoder()

In [5]:
encoder.fit_transform(labels) # fit transform is used for training data

array([0, 1, 2], dtype=int64)

In [6]:
more_labels = ['versicolor','setosa','virginica','setosa','versicolor']

In [7]:
new_labels=encoder.transform(more_labels) # transform is used in testing data
new_labels

array([1, 0, 2, 0, 1])

# Example encoding categorical data

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
# importing dataset
data = pd.read_csv('dataset/Data.csv')

In [10]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [11]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [12]:
X= data.iloc[:,:-1].values # X for input data 
Y= data.iloc[:,-1].values #y for output data

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [15]:
#MISSING DATA
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

X[:,1:3]=imputer.fit_transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [16]:
X.shape

(10, 3)

In [17]:
data.Country.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [21]:
#One hot Encoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

#Country Column
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])],
                      remainder = 'drop')
X1 = ct.fit_transform(X)

In [22]:
X1

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [24]:
#One Hot Encoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

#Contry Column
ct= ColumnTransformer([("Country", OneHotEncoder(), [0])],
                     remainder = 'passthrough')
X = ct.fit_transform(X)

In [25]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [26]:
type(X)

numpy.ndarray

In [34]:
df=pd.DataFrame(X,columns=['France','Germany','Spain','Age','Salary'])
df
df.dtype=int
df

France Germany Spain        Age        Salary
0    1.0     0.0   0.0       44.0       72000.0
1    0.0     0.0   1.0       27.0       48000.0
2    0.0     1.0   0.0       30.0       54000.0
3    0.0     0.0   1.0       38.0       61000.0
4    0.0     1.0   0.0       40.0  63777.777778
5    1.0     0.0   0.0       35.0       58000.0
6    0.0     0.0   1.0  38.777778       52000.0
7    1.0     0.0   0.0       48.0       79000.0
8    0.0     1.0   0.0       50.0       83000.0
9    1.0     0.0   0.0       37.0       67000.0

In [36]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [39]:
label_Y = LabelEncoder()
y = label_Y.fit_transform(Y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])