In [37]:
import pandas as pd
import numpy as np

In [38]:
df=pd.read_csv("dataset/fruits.csv")

In [4]:
df

diameter  weight FruitName
0        3.0      30    Banana
1        6.0     100     Apple
2        6.1      95     Apple
3        3.2      35    Banana
4        5.5      80     Apple
5        7.1     120    Banana
6        2.5      60    Banana
7        2.3     100    Banana
8        4.8      70     Apple
9        4.8      79     Apple
10       5.8     120     Apple
11       2.6      85    Banana
12       6.0     110     Apple
13       6.3      95     Apple
14       3.0      40    Banana
15       3.5      25    Banana
16       5.5     100     Apple
17       7.5     120     Apple
18       2.5      50    Banana
19       2.7      40    Banana
20       4.8      90     Apple
21       5.8      90     Apple

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   diameter   22 non-null     float64
 1   weight     22 non-null     int64  
 2   FruitName  22 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 660.0+ bytes


In [6]:
df.isnull().sum()

diameter     0
weight       0
FruitName    0
dtype: int64

In [7]:
dummies= pd.get_dummies(df.FruitName,dtype=int)
dummies

Apple  Banana
0       0       1
1       1       0
2       1       0
3       0       1
4       1       0
5       0       1
6       0       1
7       0       1
8       1       0
9       1       0
10      1       0
11      0       1
12      1       0
13      1       0
14      0       1
15      0       1
16      1       0
17      1       0
18      0       1
19      0       1
20      1       0
21      1       0

In [9]:
df.shape

(22, 3)

In [10]:
merged = pd.concat([df,dummies],axis='columns')
merged

diameter  weight FruitName  Apple  Banana
0        3.0      30    Banana      0       1
1        6.0     100     Apple      1       0
2        6.1      95     Apple      1       0
3        3.2      35    Banana      0       1
4        5.5      80     Apple      1       0
5        7.1     120    Banana      0       1
6        2.5      60    Banana      0       1
7        2.3     100    Banana      0       1
8        4.8      70     Apple      1       0
9        4.8      79     Apple      1       0
10       5.8     120     Apple      1       0
11       2.6      85    Banana      0       1
12       6.0     110     Apple      1       0
13       6.3      95     Apple      1       0
14       3.0      40    Banana      0       1
15       3.5      25    Banana      0       1
16       5.5     100     Apple      1       0
17       7.5     120     Apple      1       0
18       2.5      50    Banana      0       1
19       2.7      40    Banana      0       1
20       4.8      90     Apple      1       0
21       5.8      90     Apple      1       0

In [11]:
final = merged.drop(['FruitName'], axis='columns')
final

diameter  weight  Apple  Banana
0        3.0      30      0       1
1        6.0     100      1       0
2        6.1      95      1       0
3        3.2      35      0       1
4        5.5      80      1       0
5        7.1     120      0       1
6        2.5      60      0       1
7        2.3     100      0       1
8        4.8      70      1       0
9        4.8      79      1       0
10       5.8     120      1       0
11       2.6      85      0       1
12       6.0     110      1       0
13       6.3      95      1       0
14       3.0      40      0       1
15       3.5      25      0       1
16       5.5     100      1       0
17       7.5     120      1       0
18       2.5      50      0       1
19       2.7      40      0       1
20       4.8      90      1       0
21       5.8      90      1       0

In [273]:
X= final.iloc[:,:-2].values # X for input data 
y= final.iloc[:,2].values #y for output data

In [274]:
X

array([[  3. ,  30. ],
       [  6. , 100. ],
       [  6.1,  95. ],
       [  3.2,  35. ],
       [  5.5,  80. ],
       [  7.1, 120. ],
       [  2.5,  60. ],
       [  2.3, 100. ],
       [  4.8,  70. ],
       [  4.8,  79. ],
       [  5.8, 120. ],
       [  2.6,  85. ],
       [  6. , 110. ],
       [  6.3,  95. ],
       [  3. ,  40. ],
       [  3.5,  25. ],
       [  5.5, 100. ],
       [  7.5, 120. ],
       [  2.5,  50. ],
       [  2.7,  40. ],
       [  4.8,  90. ],
       [  5.8,  90. ]])

In [275]:
y

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1])

In [276]:
from sklearn.model_selection import train_test_split

In [277]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=10)

In [278]:
X_train.shape

(15, 2)

In [279]:
X_test.shape

(7, 2)

In [280]:
from sklearn.neighbors import KNeighborsClassifier

In [281]:
knn=KNeighborsClassifier()

In [282]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [283]:
pred=knn.predict(X_test)

In [284]:
pred[2]

1

In [285]:
y_test[2]

1

In [286]:
from sklearn.metrics import accuracy_score

In [287]:
accuracy_score(y_test,pred)

0.5714285714285714

In [288]:
import numpy as np
np.where(pred!=y_test)

(array([1, 3, 4], dtype=int64),)

In [290]:
print("Training Accuracy:",knn.score(X_train,y_train))
print("Testing Accuracy:",knn.score(X_test,y_test))

Training Accuracy: 0.9333333333333333
Testing Accuracy: 0.5714285714285714


In [291]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load the dataset
data = {
    'diameter': [3.0, 6.0, 6.1, 3.2, 5.5, 7.1, 2.5, 2.3, 4.8, 4.8, 5.8, 2.6, 6.0, 6.3, 3.0, 3.5, 5.5, 7.5, 2.5, 2.7, 4.8, 5.8],
    'weight': [30, 100, 95, 35, 80, 120, 60, 100, 70, 79, 120, 85, 110, 95, 40, 25, 100, 120, 50, 40, 90, 90],
    'FruitName': ['Banana', 'Apple', 'Apple', 'Banana', 'Apple', 'Banana', 'Banana', 'Banana', 'Apple', 'Apple', 'Apple', 'Banana', 'Apple', 'Apple', 'Banana', 'Banana', 'Apple', 'Apple', 'Banana', 'Banana', 'Apple', 'Apple'],
    'Apple': [0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
    'Banana': [1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0]
}

df = pd.DataFrame(data)

# Encode the target variable (if not already encoded)
# Here, we use the 'Banana' column to indicate whether it's a banana or not
y = df['Banana']

# Features (X)
X = df[['diameter', 'weight']]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

# Scale the features (since KNN is distance-based)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train the KNN model
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Compare predictions with actual test labels
print("Predictions: ", y_pred)
print("Actual: ", y_test.values)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Make a prediction for a new fruit (example: diameter=5.0, weight=85)
new_fruit = [[5.0, 85]]

# Scale the new data point using the same scaler
new_fruit_scaled = scaler.transform(new_fruit)

# Predict the class (0 for Apple, 1 for Banana)
pred_fruit = knn.predict(new_fruit_scaled)
print("Predicted class for new fruit (1=Banana, 0=Apple):", pred_fruit[0])


Predictions:  [1 0 0 1 1 1 1]
Actual:  [1 1 0 1 1 1 1]
Accuracy: 0.8571428571428571
Predicted class for new fruit (1=Banana, 0=Apple): 0


C:\Users\sneha\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [292]:
print("Testing Accuracy:",knn.score(X_test,y_test))

Testing Accuracy: 0.8571428571428571
