# Iris Dataset Model Training Using KNN Algo



In [ ]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
X=iris.data

In [5]:
X.shape 

(150, 4)

In [6]:
y=iris.target

In [7]:
y.shape

(150,)

# Split data into training & testing:-


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=30,random_state=10)

In [10]:
X_train

array([[6.6, 2.9, 4.6, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.8, 5.1, 2.4],
       [6.3, 2.5, 5. , 1.9],
       [4.6, 3.2, 1.4, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 2.7, 3.9, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [4.7, 3.2, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3

In [11]:
X_train.shape

(120, 4)

In [12]:
X_test.shape

(30, 4)

In [13]:
y_train.shape

(120,)

In [14]:
y_test.shape

(30,)

# 2. Import Algo / Model / Classifier / Estimator

In [15]:
from sklearn.neighbors import KNeighborsClassifier

# 3. Create a Object of Model:-

In [16]:
knn=KNeighborsClassifier()

# 4. Train Model with Taining Data:-

In [17]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

# 5. Making Prediction of Unseen Data or Testing Data

In [18]:
pred=knn.predict(X_test)

In [19]:
pred


array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [20]:
pred[0]

1

In [21]:
y_test[0]

1

In [22]:
pred[1]

2

In [23]:
y_test[1]

2

In [24]:
# How to find out Misclassified Sample

In [25]:
import numpy as np
np.where(pred!=y_test)

(array([6], dtype=int64),)

In [26]:
pred[6]

2

In [27]:
y_test[6]

1

# 6. Evaluation:-

In [29]:
from sklearn.metrics import accuracy_score # metrics is module

In [30]:
accuracy_score(y_test,pred) # accuracy is method

0.9666666666666667

In [31]:
print("Training Accuracy:",knn.score(X_train,y_train))
print("Testing Accuracy:",knn.score(X_test,y_test))

Training Accuracy: 0.975
Testing Accuracy: 0.9666666666666667


In [32]:
pred

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [33]:
pred[0]

1

In [34]:
y_test[0]

1

In [35]:
X_test[0]

array([6.3, 2.3, 4.4, 1.3])

In [36]:
X_test[0].reshape(1,-1)


array([[6.3, 2.3, 4.4, 1.3]])

# How to find out nearest neighbors

In [37]:
d,index=knn.kneighbors(X_test[0].reshape(1,-1),n_neighbors=5,return_distance=True)

In [38]:
d

array([[0.26457513, 0.59160798, 0.60827625, 0.6164414 , 0.6164414 ]])

In [39]:
index

array([[ 20, 101, 105,   1,  72]], dtype=int64)

In [40]:
for i in index:
    print(y_train[i])

[1 1 1 1 1]


# How to find out misclassified sample

In [48]:
import numpy as np
np.where(pred!=y_test)

(array([6], dtype=int64),)

In [49]:
pred[6]

2

In [50]:
y_test[6]

1

In [51]:
#Evaluation Result is class 0 & class2 , prediction is correct & class 1 prediction is 4%

# Confusion Matrix:-

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
c_m=confusion_matrix(y_test,pred)
c_m

array([[10,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  7]], dtype=int64)

# Precision & Recall:-

In [57]:
 from sklearn.metrics import precision_score,recall_score,f1_score,classification_report

In [58]:
precision_score(y_test,pred,average='macro')

0.9583333333333334

In [59]:
recall_score(y_test,pred,average='macro')

0.9743589743589745

In [60]:
f1_score(y_test,pred,average='macro')

0.9644444444444445

In [61]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.92      0.96        13
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

