# Goal 

## Design a model that is able to automatically recognize IRIS species


Load training dataset

### 1.Collect data:-

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.frame

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris.filename

'iris.csv'

In [11]:
iris.data_module

'sklearn.datasets.data'

In [12]:
n_samples,features=iris.data.shape
print("No. of Samples",n_samples)
print("No. of Features",features)

No. of Samples 150
No. of Features 4


In [13]:
import numpy as np
np.unique(iris.target)

array([0, 1, 2])

In [14]:
np.bincount(iris.target)

array([50, 50, 50], dtype=int64)

In [15]:
X=iris.data

In [16]:
X.shape

(150, 4)

In [17]:
y=iris.target

In [18]:
y.shape

(150,)

In [19]:
X.ndim

2

In [20]:
y.ndim

1

In [21]:
import pandas as pd
df=pd.DataFrame(X,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [22]:
df['target']=y

In [23]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
data=df.values

In [25]:
data[:20]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ]])

In [26]:
np.random.shuffle(data)

In [27]:
data[:20]

array([[4.8, 3. , 1.4, 0.1, 0. ],
       [5.1, 3.5, 1.4, 0.2, 0. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [4.6, 3.2, 1.4, 0.2, 0. ],
       [5.5, 2.5, 4. , 1.3, 1. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [5.1, 3.8, 1.9, 0.4, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [6.3, 2.8, 5.1, 1.5, 2. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [5.6, 2.7, 4.2, 1.3, 1. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.1, 3.8, 1.6, 0.2, 0. ]])

In [28]:
X_train,y_train=data[:120,:-1],data[:120,-1]

In [29]:
X_train.shape

(120, 4)

In [30]:
y_train.shape

(120,)

In [31]:
X_train[:10]

array([[4.8, 3. , 1.4, 0.1],
       [5.1, 3.5, 1.4, 0.2],
       [6.1, 2.8, 4.7, 1.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 4.7, 1.5],
       [5.7, 2.9, 4.2, 1.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3. , 1.6, 0.2]])

In [32]:
y_train[:10]

array([0., 0., 1., 0., 1., 2., 1., 1., 0., 0.])

In [33]:
X_test,y_test=data[120:,:-1],data[120:,-1]

In [34]:
X_test.shape

(30, 4)

In [35]:
y_test.shape

(30,)

# how to split data into training and testing using sklearn

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=30,random_state=10)

In [37]:
X_train.shape

(120, 4)

In [38]:
y_train.shape

(120,)

In [39]:
X_test.shape

(30, 4)

In [40]:
y_test.shape

(30,)

# 2. Import Algo/ Model/Classifier/Estimator

In [41]:
from sklearn.neighbors import KNeighborsClassifier

# 3. Create Object of Model:-

In [42]:
knn=KNeighborsClassifier()

# 4. Train Model with training data

In [43]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

# 5. Making Prediction of Unseen Data or Testing Data

In [44]:
pred=knn.predict(X_test)

In [45]:
pred

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [46]:
pred[0]

1

In [47]:
y_test[0]

1

# How to find out Misclassified Sample:-

In [48]:
import numpy as np
np.where(pred!=y_test)

(array([6], dtype=int64),)

In [49]:
pred[6]

2

In [50]:
y_test[6]

1

# 6.Evaluation:-

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
accuracy_score(y_test,pred)

0.9666666666666667

In [53]:
print("Training Accuracy:",knn.score(X_train,y_train))
print("Tesing Accuracy:",knn.score(X_test,y_test))

Training Accuracy: 0.975
Tesing Accuracy: 0.9666666666666667


In [54]:
pred

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [68]:
pred[1]

2

In [69]:
y_test[1]

2

In [57]:
X_test[0]

array([6.3, 2.3, 4.4, 1.3])

In [58]:
#How to convert one d to 2 d
X_test[0].reshape(1,-1)

array([[6.3, 2.3, 4.4, 1.3]])

# How to find out Nearest Neighbors

In [70]:
d,index=knn.kneighbors(X_test[1].reshape(1,-1),n_neighbors=5,return_distance=True)

In [71]:
d

array([[0.34641016, 0.37416574, 0.37416574, 0.38729833, 0.38729833]])

In [72]:
index

array([[69, 51,  4, 43, 59]], dtype=int64)

In [73]:
for i in index:
    print(y_train[i])

[2 2 2 2 2]
